// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcCk87jZ_nODlJ9HEaiYY1E-FbqSflBDA',
    appId: '1:190250686656:android:a65e3aab77bcbcd18c3525',
    messagingSenderId: '190250686656',
    projectId: 'belle-app-1ef26',
    storageBucket: 'belle-app-1ef26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_aChFfQ85FXQqKd_Yz7QvNzcfkMRc1c',
    appId: '1:190250686656:ios:c601d66b703028ea8c3525',
    messagingSenderId: '190250686656',
    projectId: 'belle-app-1ef26',
    storageBucket: 'belle-app-1ef26.firebasestorage.app',
    androidClientId: '190250686656-9cqv6v3dqbjcn903vtnbc5fp4qb4e7l2.apps.googleusercontent.com',
    iosClientId: '190250686656-38b1k3po3sv0a759ur6o9hpb015vbqdf.apps.googleusercontent.com',
    iosBundleId: 'com.belle.belle',
  );

}